<?php
/**
 * @copyright Copyright (c) 2024 Magebit, Ltd. (https://magebit.com/)
 * @author    Magebit <info@magebit.com>
 * @license   MIT
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */

?>
<?php /* The wire Payment Method directive is required to sit in the root DOM element. */ ?>
<div>
    <p class="p-4 bg-gray-100 rounded-lg">
        <?= __('You will be redirected to the Viva Wallet Gateway to complete payment.') ?>
    </p>
</div>
